MAX_PROJECTS_PER_USER = 5
DEFAULT_CHAT_PAGE_SIZE = 20
MAX_CHAT_PAGE_SIZE = 100
SUPPORTED_DATASET_EXTENSIONS = {".csv", ".xls", ".xlsx"}
DATASETS_DIRNAME = "datasets"
NOTEBOOKS_DIRNAME = "notebooks"

RECENT_MESSAGES_WINDOW = 10
SUMMARY_THRESHOLD = 20
MAX_CONTEXT_TOKENS = 4000
SUMMARY_PROMPT_TOKENS = 500
